#ifndef USB_DESCRIPTORS_H_
#define USB_DESCRIPTORS_H_

#include "tusb.h"

enum {
	ITF_NUM_KEYBOARD = 0,
	ITF_NUM_MIDI,
	ITF_NUM_MIDI_STREAMING,
	ITF_TOTAL
};

enum {
	STRID_LANGID = 0,
	STRID_MANUFACTURER,
	STRID_PRODUCT,
	STRID_SERIAL,
	STRID_KEYBOARD,
	STRID_MIDI
};

#define EPNUM_KEYBOARD 0x81
#define EPNUM_MIDI_OUT 0x02
#define EPNUM_MIDI_IN  0x82

#endif /* USB_DESCRIPTORS_H_ */
